site_name: Documentation de PluXml
site_url: https://www.pluxml.org/
site_description: Documentation de PluXml
site_author: PluXml staff

repo_name: GitHub
repo_url: 'https://github.com/pluxml/'
edit_uri: https://github.com/pluxml/

markdown_extensions:
    - admonition

theme:
    name: mkdocs
    custom_dir: custom_theme/

nav:
- Installer: installer/installation.md
- Utiliser: utiliser/utilisation.md
- Personnaliser: personnaliser/personnalisation.md
- DÃ©velopper: developper/developpement.md
- Contribuer: contribuer/contribuer.md
- Plugins officiels: divers/plugins-officiels.md
- Plugins non officiels: divers/plugins-non-officiels.md
- Divers: divers/divers-autre.md
